Reduce the time a Mercedes-Benz spends on the test bench.

Problem Statement Scenario:
Since the first automobile, the Benz Patent Motor Car in 1886, Mercedes-Benz has stood for important automotive innovations. These include the passenger safety cell with a crumple zone, the airbag, and intelligent assistance systems. Mercedes-Benz applies for nearly 2000 patents per year, making the brand the European leader among premium carmakers. Mercedes-Benz is the leader in the premium car industry. With a huge selection of features and options, customers can choose the customized Mercedes-Benz of their dreams.

To ensure the safety and reliability of every unique car configuration before they hit the road, the company’s engineers have developed a robust testing system. As one of the world’s biggest manufacturers of premium cars, safety and efficiency are paramount on Mercedes-Benz’s production lines. However, optimizing the speed of their testing system for many possible feature combinations is complex and time-consuming without a powerful algorithmic approach.

You are required to reduce the time that cars spend on the test bench. Others will work with a dataset representing different permutations of features in a Mercedes-Benz car to predict the time it takes to pass testing. Optimal algorithms will contribute to faster testing, resulting in lower carbon dioxide emissions without reducing Mercedes-Benz’s standards.

Following actions should be performed:


If for any column(s), the variance is equal to zero, then you need to remove those variable(s).

Check for null and unique values for test and train sets.

Apply label encoder.

Perform dimensionality reduction.

Predict your test_df values using XGBoost.

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
df_train= pd.read_csv("C:\\Users\\shiva\\Downloads\\train\\train.csv")
df_train

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4207,8415,87.48,al,r,e,f,d,aa,l,u,...,0,0,0,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

In [3]:
df_test= pd.read_csv("C:\\Users\\shiva\\Downloads\\test\\test.csv")
df_test

,ID,X0,X1,X2,X3,X4,X5,X6,X8,X10,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,1,az,v,n,f,d,t,a,w,0,...,0,0,0,1,0,0,0,0,0,0
1,2,t,b,ai,a,d,b,g,y,0,...,0,0,1,0,0,0,0,0,0,0
2,3,az,v,as,f,d,a,j,j,0,...,0,0,0,1,0,0,0,0,0,0
3,4,az,l,n,f,d,z,l,n,0,...,0,0,0,1,0,0,0,0,0,0
4,5,w,s,as,c,d,y,i,m,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,8410,aj,h,as,f,d,aa,j,e,0,...,0,0,0,0,0,0,0,0,0,0
4205,8411,t,aa,ai,d,d,aa,j,y,0,...,0,1,0,0,0,0,0,0,0,0
4206,8413,y,v,as,f,d,aa,d,w,0,...,0,0,0,0,0,0,0,0,0,0
4207,8414,ak,v,as,a,d,aa,c,q,0,...,0,0,1,0,0,0,0,0,0,0
4208,8416,t,aa,ai,c,d,aa,g,r,0,...,1,0,0,0,0,0,0,0,0,0

In [4]:
y_train= df_train['y'].values
id_test= df_test['ID'].values

In [5]:
usable_columns= list(set(df_train.columns) - set(['ID', 'y']))
x_train= df_train[usable_columns]
x_test= df_test[usable_columns]

In [6]:
# Check for null and unique values for test and train sets.

def check_missing_values(df):
    if df.isnull().any().any():
        print("There are missing values in the dataframe")
    else:
        print("There are no missing values in the dataframe")
check_missing_values(x_train)
check_missing_values(x_test)

There are no missing values in the dataframe
There are no missing values in the dataframe

In [7]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()

In [8]:
# Apply label encoder.

x_train[usable_columns]= x_train[usable_columns].apply(le.fit_transform)
x_train

,X376,X61,X20,X145,X353,X345,X340,X136,X377,X233,...,X4,X55,X45,X186,X309,X341,X76,X344,X330,X289
0,0,0,0,0,0,0,0,1,1,0,...,3,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,1,0,0,...,3,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,3,0,0,0,0,0,1,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,3,0,0,0,0,0,1,0,0,0
4,0,1,0,0,0,0,0,0,0,0,...,3,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,0,1,0,0,0,0,0,1,0,0,...,3,0,0,0,0,0,0,0,0,0
4205,1,1,0,0,0,0,0,1,0,0,...,3,0,0,1,0,0,0,0,0,0
4206,0,1,0,0,0,0,0,1,1,0,...,3,0,0,0,0,0,0,0,0,0
4207,0,1,0,0,0,0,0,1,0,0,...,3,0,0,1,0,0,0,0,0,0
4208,0,1,1,0,0,0,0,1,0,0,...,3,0,0,1,0,0,0,0,0,0

In [9]:
# Apply label encoder.

x_test[usable_columns]= x_test[usable_columns].apply(le.fit_transform)
x_test

,X376,X61,X20,X145,X353,X345,X340,X136,X377,X233,...,X4,X55,X45,X186,X309,X341,X76,X344,X330,X289
0,0,1,0,0,0,0,0,0,0,0,...,3,0,0,0,0,0,1,0,0,0
1,0,1,0,0,0,0,0,1,1,0,...,3,0,1,1,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,3,0,0,0,0,0,1,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,3,0,0,0,0,0,1,0,0,0
4,0,1,0,0,0,0,0,1,0,0,...,3,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,0,1,0,0,0,0,0,1,0,0,...,3,0,0,0,0,0,0,0,0,0
4205,1,1,0,0,0,0,0,1,0,0,...,3,0,0,1,0,0,0,0,0,0
4206,0,1,0,0,0,0,0,1,0,0,...,3,0,0,1,0,0,0,0,0,0
4207,0,1,0,0,0,0,0,1,1,0,...,3,0,0,0,0,0,0,0,0,0
4208,0,1,0,0,0,0,0,1,0,0,...,3,0,0,1,0,0,0,0,0,0

In [10]:
# If for any column(s), the variance is equal to zero, then you need to remove those variable(s).

for column in usable_columns:
    if x_train[column].var() == 0:
        x_train.drop(column, axis= 1, inplace= True)
        x_test.drop(column, axis= 1, inplace= True)

x_train

,X376,X61,X20,X145,X353,X345,X340,X136,X377,X132,...,X161,X254,X4,X55,X45,X186,X309,X341,X76,X344
0,0,0,0,0,0,0,0,1,1,0,...,0,0,3,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,1,0,1,...,0,0,3,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,1,...,0,0,3,0,0,0,0,0,1,0
3,0,1,0,0,0,0,0,0,0,1,...,0,0,3,0,0,0,0,0,1,0
4,0,1,0,0,0,0,0,0,0,1,...,0,0,3,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,0,1,0,0,0,0,0,1,0,1,...,0,0,3,0,0,0,0,0,0,0
4205,1,1,0,0,0,0,0,1,0,1,...,0,0,3,0,0,1,0,0,0,0
4206,0,1,0,0,0,0,0,1,1,1,...,0,0,3,0,0,0,0,0,0,0
4207,0,1,0,0,0,0,0,1,0,1,...,0,0,3,0,0,1,0,0,0,0
4208,0,1,1,0,0,0,0,1,0,1,...,0,0,3,0,0,1,0,0,0,0

In [11]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 364 entries, X376 to X344
dtypes: int32(8), int64(356)
memory usage: 11.6 MB

In [12]:
from sklearn.decomposition import PCA

In [13]:
# Perform dimensionality reduction.

pca= PCA(n_components= 10)
pca_train= pca.fit_transform(x_train)
pca_test= pca.transform(x_test)

In [14]:
import xgboost as xgb
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [15]:
x_train, x_valid, y_train, y_valid= train_test_split(pca_train, y_train, test_size= 0.2, random_state= 1)

In [16]:
xgb_train= xgb.DMatrix(x_train, label= y_train)
xgb_valid= xgb.DMatrix(x_valid, label= y_valid)
xgb_test= xgb.DMatrix(pca_test)

In [17]:
# training our dataset using XGBOOST 

params= {}
params['objective'] = 'reg:linear'
params['eta'] = 0.02
params['max_depth'] = 4

def xgb_r2_score(preds, dtrain):
    labels = dtrain.get_label()
    return 'r2', r2_score(labels, preds)

watchlist = [(xgb_train, 'train'), (xgb_valid, 'valid')]

clf = xgb.train(params, xgb_train, 
                1000, watchlist, early_stopping_rounds=50, 
                feval=xgb_r2_score, maximize=True, verbose_eval=10)

[23:32:40] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.6.0/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.
[0]	train-rmse:99.01401	train-r2:-60.24932	valid-rmse:98.82777	valid-r2:-58.79043
[10]	train-rmse:81.17027	train-r2:-40.16251	valid-rmse:81.03226	valid-r2:-39.19662
[20]	train-rmse:66.62917	train-r2:-26.73554	valid-rmse:66.53576	valid-r2:-26.10091
[30]	train-rmse:54.79422	train-r2:-17.75760	valid-rmse:54.73119	valid-r2:-17.33764
[40]	train-rmse:45.17805	train-r2:-11.75155	valid-rmse:45.13058	valid-r2:-11.46854
[50]	train-rmse:37.38808	train-r2:-7.73322	valid-rmse:37.36038	valid-r2:-7.54469
[60]	train-rmse:31.10158	train-r2:-5.04328	valid-rmse:31.10463	valid-r2:-4.92276
[70]	train-rmse:26.05829	train-r2:-3.24228	valid-rmse:26.10836	valid-r2:-3.17285
[80]	train-rmse:22.03849	train-r2:-2.03439	valid-rmse:22.13303	valid-r2:-1.99886
[90]	train-rmse:18.86716	train-r2:-1.22393	valid-rmse:19.00393	valid-r2:-1.21086
[100]	train-rmse:16.39433	train-r2:-0.67917	valid-rmse:16.58349	valid-r2:-0.68355
[110]	train-rmse:14.48765	train-r2:-0.31130	valid-rmse:14.72551	valid-r2:-0.32744
[120]	train-rmse:13.03336	train-r2:-0.06126	valid-rmse:13.34760	valid-r2:-0.09064
[130]	train-rmse:11.93729	train-r2:0.10973	valid-rmse:12.33283	valid-r2:0.06889
[140]	train-rmse:11.12114	train-r2:0.22731	valid-rmse:11.58486	valid-r2:0.17841
[150]	train-rmse:10.51376	train-r2:0.30940	valid-rmse:11.04055	valid-r2:0.25380
[160]	train-rmse:10.07112	train-r2:0.36633	valid-rmse:10.65027	valid-r2:0.30562
[170]	train-rmse:9.73118	train-r2:0.40838	valid-rmse:10.37158	valid-r2:0.34149
[180]	train-rmse:9.48166	train-r2:0.43834	valid-rmse:10.17063	valid-r2:0.36676
[190]	train-rmse:9.28134	train-r2:0.46182	valid-rmse:10.03976	valid-r2:0.38295
[200]	train-rmse:9.12715	train-r2:0.47955	valid-rmse:9.93532	valid-r2:0.39572
[210]	train-rmse:9.01250	train-r2:0.49254	valid-rmse:9.87079	valid-r2:0.40354
[220]	train-rmse:8.91029	train-r2:0.50399	valid-rmse:9.81783	valid-r2:0.40993
[230]	train-rmse:8.82839	train-r2:0.51306	valid-rmse:9.78491	valid-r2:0.41388
[240]	train-rmse:8.74994	train-r2:0.52168	valid-rmse:9.75204	valid-r2:0.41781
[250]	train-rmse:8.67992	train-r2:0.52931	valid-rmse:9.72746	valid-r2:0.42074
[260]	train-rmse:8.63016	train-r2:0.53469	valid-rmse:9.70578	valid-r2:0.42332
[270]	train-rmse:8.57585	train-r2:0.54053	valid-rmse:9.69288	valid-r2:0.42485
[280]	train-rmse:8.51891	train-r2:0.54661	valid-rmse:9.67454	valid-r2:0.42703
[290]	train-rmse:8.48024	train-r2:0.55071	valid-rmse:9.66488	valid-r2:0.42817
[300]	train-rmse:8.44192	train-r2:0.55476	valid-rmse:9.64924	valid-r2:0.43002
[310]	train-rmse:8.41094	train-r2:0.55803	valid-rmse:9.63962	valid-r2:0.43116
[320]	train-rmse:8.36891	train-r2:0.56243	valid-rmse:9.63098	valid-r2:0.43217
[330]	train-rmse:8.34017	train-r2:0.56543	valid-rmse:9.62546	valid-r2:0.43283
[340]	train-rmse:8.31121	train-r2:0.56844	valid-rmse:9.61740	valid-r2:0.43378
[350]	train-rmse:8.28203	train-r2:0.57147	valid-rmse:9.61185	valid-r2:0.43443
[360]	train-rmse:8.25773	train-r2:0.57398	valid-rmse:9.60598	valid-r2:0.43512
[370]	train-rmse:8.23068	train-r2:0.57677	valid-rmse:9.60301	valid-r2:0.43547
[380]	train-rmse:8.20328	train-r2:0.57958	valid-rmse:9.59816	valid-r2:0.43604
[390]	train-rmse:8.17718	train-r2:0.58225	valid-rmse:9.59431	valid-r2:0.43649
[400]	train-rmse:8.14827	train-r2:0.58520	valid-rmse:9.58399	valid-r2:0.43770
[410]	train-rmse:8.12137	train-r2:0.58793	valid-rmse:9.57292	valid-r2:0.43900
[420]	train-rmse:8.09505	train-r2:0.59060	valid-rmse:9.56501	valid-r2:0.43993
[430]	train-rmse:8.06788	train-r2:0.59334	valid-rmse:9.55568	valid-r2:0.44102
[440]	train-rmse:8.04189	train-r2:0.59596	valid-rmse:9.55274	valid-r2:0.44136
[450]	train-rmse:8.01839	train-r2:0.59832	valid-rmse:9.55107	valid-r2:0.44156
[460]	train-rmse:7.99510	train-r2:0.60065	valid-rmse:9.54281	valid-r2:0.44252
[470]	train-rmse:7.96526	train-r2:0.60362	valid-rmse:9.53991	valid-r2:0.44286
[480]	train-rmse:7.93922	train-r2:0.60621	valid-rmse:9.54024	valid-r2:0.44282
[490]	train-rmse:7.91517	train-r2:0.60859	valid-rmse:9.53432	valid-r2:0.44352
[500]	train-rmse:7.88834	train-r2:0.61124	valid-rmse:9.52783	valid-r2:0.44427
[510]	train-rmse:7.85751	train-r2:0.61428	valid-rmse:9.52289	valid-r2:0.44485
[520]	train-rmse:7.83622	train-r2:0.61636	valid-rmse:9.52311	valid-r2:0.44482
[530]	train-rmse:7.81022	train-r2:0.61890	valid-rmse:9.52178	valid-r2:0.44498
[540]	train-rmse:7.78450	train-r2:0.62141	valid-rmse:9.51927	valid-r2:0.44527
[550]	train-rmse:7.76144	train-r2:0.62365	valid-rmse:9.51674	valid-r2:0.44556
[560]	train-rmse:7.74115	train-r2:0.62561	valid-rmse:9.52047	valid-r2:0.44513
[570]	train-rmse:7.72031	train-r2:0.62763	valid-rmse:9.51895	valid-r2:0.44531
[580]	train-rmse:7.69334	train-r2:0.63023	valid-rmse:9.51864	valid-r2:0.44534
[590]	train-rmse:7.67343	train-r2:0.63214	valid-rmse:9.52095	valid-r2:0.44507
[595]	train-rmse:7.65908	train-r2:0.63351	valid-rmse:9.52142	valid-r2:0.44502

In [18]:
# Predict your test_df values using XGBoost.

p_test = clf.predict(xgb_test)

sub = pd.DataFrame()
sub['ID'] = id_test
sub['y'] = p_test
sub.to_csv('xgb.csv', index=False)

sub.head()

   ID           y
0   1   83.337997
1   2   95.740608
2   3   90.487030
3   4   75.920425
4   5  111.323433